<?php

$continents =[
    [
        'name' => 'amérique',
        'image' => 'images/navbar/Amérique Continent.png'
    ],
    [
        'name' => 'asie',
        'image' => 'images/navbar/Asie Continent.png'
    ],
    [
        'name' => 'europe',
        'image' => 'images/navbar/Europe Continent.png'
    ],
    [
        'name' => 'océanie',
        'image' => 'images/navbar/Océanie Continent.png'
    ],
];

$teams = [ 
    [
        'name' => 'redbull',
        'fullname' => 'oracle red bull racing',
        'logo' => 'images/logos/Red Bull Logo.png',
        'livery' => 'images/liveries/Red Bull Livery.png',
        'director' => 'christian horner',
        'driver1' => 'max verstappen',
        'driver2' => 'sergio pérez',
    ],
    [
        'name' => 'mercedes',
        'fullname' => 'mercedes-amg petronas f1 team',
        'logo' => 'images/logos/Mercedes Logo.png',
        'livery' => 'images/liveries/Mercedes Livery.png',
        'director' => 'toto wolff',
        'driver1' => 'lewis hamilton',
        'driver2' => 'george russell',
    ],
    [
        'name' => 'ferrari',
        'fullname' => 'scuderia ferrari',
        'logo' => 'images/logos/Ferrari Logo.png',
        'livery' => 'images/liveries/Ferrari Livery.png',
        'director' => 'frédéric vasseur',
        'driver1' => 'charles leclerc',
        'driver2' => 'carlos sainz jr',
    ],
    [
        'name' => 'mclaren',
        'fullname' => 'mclaren formula 1 team',
        'logo' => 'images/logos/McLaren Logo.png',
        'livery' => 'images/liveries/McLaren Livery.png',
        'director' => 'andrea stella',
        'driver1' => 'lando norris',
        'driver2' => 'oscar piastri',
    ],
    [
        'name' => 'astonmartin',
        'fullname' => 'aston martin aramco f1 team',
        'logo' => 'images/logos/Aston Martin Logo.png',
        'livery' => 'images/liveries/Aston Martin Livery.png',
        'director' => 'mike krack',
        'driver1' => 'fernando alonso',
        'driver2' => 'lance stroll',
    ],
    [
        'name' => 'alpine',
        'fullname' => 'bwt alpine f1 team',
        'logo' => 'images/logos/Alpine Logo.png',
        'livery' => 'images/liveries/Alpine Livery.png',
        'director' => 'bruno famin',
        'driver1' => 'pierre gasly',
        'driver2' => 'esteban ocon',
    ],
    [
        'name' => 'williams',
        'fullname' => 'williams racing',
        'logo' => 'images/logos/Williams Logo.png',
        'livery' => 'images/liveries/Williams Livery.png',
        'director' => 'james vowles',
        'driver1' => 'alexander albon',
        'driver2' => 'logan sargeant',
    ],
    [
        'name' => 'rb',
        'fullname' => 'visa cash app rb formula one team',
        'logo' => 'images/logos/Racing Bulls Logo.png',
        'livery' => 'images/liveries/Racing Bulls Livery.png',
        'director' => 'laurent mekies',
        'driver1' => 'yuki tsunoda',
        'driver2' => 'daniel ricciardo',
    ],
    [
        'name' => 'kick',
        'fullname' => 'stake f1 team kick sauber',
        'logo' => 'images/logos/Kick Logo.png',
        'livery' => 'images/liveries/Kick Livery.png',
        'director' => 'alessandro alunni bravi',
        'driver1' => 'valtteri bottas',
        'driver2' => 'guanyu zhou',
    ],
    [
        'name' => 'haas',
        'fullname' => 'moneygram haas f1 team',
        'logo' => 'images/logos/Haas Logo.png',
        'livery' => 'images/liveries/Haas Livery.png',
        'director' => 'ayao komatsu',
        'driver1' => 'nico hulkenberg',
        'driver2' => 'kevin magnussen',
    ],
];

$teamsMembers = [
    // Nom => "name" / Prénom => "firstname" (Convention)   (fait)
    [
        'name' => 'verstappen',
        'firstname' => 'max',
        'photo' => 'images/drivers/Max Verstappen.png',
        'role' => 'driver',
        'team' => 'redbull',
    ],
    [
        'name' => 'pérez',
        'firstname' => 'sergio',
        'photo' => 'images/drivers/Sergio Pérez.png',
        'role' => 'driver',
        'team' => 'redbull',
    ],
    [
        'name' => 'horner',
        'firstname' => 'christian',
        'photo' => '',
        'role' => 'director',
        'team' => 'redbull',
    ],
    [
        'name' => 'hamilton',
        'firstname' => 'lewis',
        'photo' => 'images/drivers/Lewis Hamilton.png',
        'role' => 'driver',
        'team' => 'mercedes',
    ],
    [
        'name' => 'russell',
        'firstname' => 'george',
        'photo' => 'images/drivers/George Russell.png',
        'role' => 'driver',
        'team' => 'mercedes',
    ],
    [
        'name' => 'wolff',
        'firstname' => 'toto',
        'photo' => '',
        'role' => 'director',
        'team' => 'mercedes',
    ],
    [
        'name' => 'leclerc',
        'firstname' => 'charles',
        'photo' => 'images/drivers/Charles Leclerc.png',
        'role' => 'driver',
        'team' => 'ferrari',
    ],
    [
        'name' => 'sainz',
        'firstname' => 'carlos',
        'photo' => 'images/drivers/Carlos Sainz Jr.png',
        'role' => 'driver',
        'team' => 'ferrari',
    ],
    [
        'name' => 'vasseur',
        'firstname' => 'frédéric',
        'photo' => '',
        'role' => 'director',
        'team' => 'ferrari',
    ],
    [
        'name' => 'norris',
        'firstname' => 'lando',
        'photo' => 'images/drivers/Lando Norris.png',
        'role' => 'driver',
        'team' => 'mclaren',
    ],
    [
        'name' => 'piastri',
        'firstname' => 'oscar',
        'photo' => 'images/drivers/Oscar Piastri.png',
        'role' => 'driver',
        'team' => 'mclaren',
    ],
    [
        'name' => 'stella',
        'firstname' => 'andrea',
        'photo' => '',
        'role' => 'director',
        'team' => 'mclaren',
    ],
    [
        'name' => 'alonso',
        'firstname' => 'fernando',
        'photo' => 'images/drivers/Fernando Alonso.png',
        'role' => 'driver',
        'team' => 'astonmartin',
    ],
    [
        'name' => 'stroll',
        'firstname' => 'lance',
        'photo' => 'images/drivers/Lance Stroll.png',
        'role' => 'driver',
        'team' => 'astonmartin',
    ],
    [
        'name' => 'krack',
        'firstname' => 'mike',
        'photo' => '',
        'role' => 'director',
        'team' => 'astonmartin',
    ],
    [
        'name' => 'gasly',
        'firstname' => 'pierre',
        'photo' => 'images/drivers/Pierre Gasly.png',
        'role' => 'driver',
        'team' => 'alpine',
    ],
    [
        'name' => 'ocon',
        'firstname' => 'esteban',
        'photo' => 'images/drivers/Esteban Ocon.png',
        'role' => 'driver',
        'team' => 'alpine',
    ],
    [
        'name' => 'famin',
        'firstname' => 'bruno',
        'photo' => '',
        'role' => 'director',
        'team' => 'alpine',
    ],
    [
        'name' => 'albon',
        'firstname' => 'alexander',
        'photo' => 'images/drivers/Alexander Albon.png',
        'role' => 'driver',
        'team' => 'williams',
    ],
    [
        'name' => 'sargeant',
        'firstname' => 'logan',
        'photo' => 'images/drivers/Logan Sargeant.png',
        'role' => 'driver',
        'team' => 'williams',
    ],
    [
        'name' => 'vowles',
        'firstname' => 'james',
        'photo' => '',
        'role' => 'director',
        'team' => 'williams',
    ],
    [
        'name' => 'tsunoda',
        'firstname' => 'yuki',
        'photo' => 'images/drivers/Yuki Tsunoda.png',
        'role' => 'driver',
        'team' => 'rb',
    ],
    [
        'name' => 'ricciardo',
        'firstname' => 'daniel',
        'photo' => 'images/drivers/Daniel Ricciardo.png',
        'role' => 'driver',
        'team' => 'rb',
    ],
    [
        'name' => 'mekies',
        'firstname' => 'laurent',
        'photo' => '',
        'role' => 'director',
        'team' => 'rb',
    ],
    [
        'name' => 'bottas',
        'firstname' => 'valtteri',
        'photo' => 'images/drivers/Valtteri Bottas.png',
        'role' => 'driver',
        'team' => 'kick',
    ],
    [
        'name' => 'zhou',
        'firstname' => 'guanyu',
        'photo' => 'images/drivers/Guanyu Zhou.png',
        'role' => 'driver',
        'team' => 'kick',
    ],
    [
        'name' => 'alunni bravi',
        'firstname' => 'alessandro',
        'photo' => '',
        'role' => 'director',
        'team' => 'kick',
    ],
    [
        'name' => 'hulkenberg',
        'firstname' => 'nico',
        'photo' => 'images/drivers/Nico Hulkenberg.png',
        'role' => 'driver',
        'team' => 'haas',
    ],
    [
        'name' => 'magnussen',
        'firstname' => 'kevin',
        'photo' => 'images/drivers/Kevin Magnussen.png',
        'role' => 'driver',
        'team' => 'haas',
    ],
    [
        'name' => 'komatsu',
        'firstname' => 'ayao',
        'photo' => '',
        'role' => 'director',
        'team' => 'haas',
    ],
];

$championships = [
    [
        'name' => 'pilote',
        'position' => 20,
        'image' => 'images/navbar/Pilote Trophée.png',
    ],
    [
        'name' => 'constructeur',
        'position' => 10,
        'image' => 'images/navbar/Constructeur Trophée.png',
    ],
];


$seasons = ['2024', '2025', '2026'];



// Remplacer 'yes' ou '' par true ou false - Par défaut = null  (fait)
$races = [
    [
        'race_name' => 'bahreïn',
        'flag' => 'images/flags/Drapeau Bahreïn.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'arabie saoudite',
        'flag' => 'images/flags/Drapeau Arabie Saoudite.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'australie',
        'flag' => 'images/flags/Drapeau Australie.png',
        'continent' => 'océanie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'japon',
        'flag' => 'images/flags/Drapeau Japon.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'chine',
        'flag' => 'images/flags/Drapeau Chine.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'miami',
        'flag' => 'images/flags/Drapeau Etats Unis.png',
        'continent' => 'amérique',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'émilie-romagne',
        'flag' => 'images/flags/Drapeau Italie.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'monaco',
        'flag' => 'images/flags/Drapeau Monaco.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'canada',
        'flag' => 'images/flags/Drapeau Canada.png',
        'continent' => 'amérique',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'espagne',
        'flag' => 'images/flags/Drapeau Espagne.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'autriche',
        'flag' => 'images/flags/Drapeau Autriche.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'grande-bretagne',
        'flag' => 'images/flags/Drapeau Grande Bretagne.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'hongrie',
        'flag' => 'images/flags/Drapeau Hongrie.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'belgique',
        'flag' => 'images/flags/Drapeau Belgique.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'pays-bas',
        'flag' => 'images/flags/Drapeau Pays Bas.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'italie',
        'flag' => 'images/flags/Drapeau Italie.png',
        'continent' => 'europe',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'azerbaïdjan',
        'flag' => 'images/flags/Drapeau Azerbaïdjan.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'singapour',
        'flag' => 'images/flags/Drapeau Singapour.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'états-unis',
        'flag' => 'images/flags/Drapeau Etats Unis.png',
        'continent' => 'amérique',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'mexique',
        'flag' => 'images/flags/Drapeau Mexique.png',
        'continent' => 'amérique',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'brésil',
        'flag' => 'images/flags/Drapeau Brésil.png',
        'continent' => 'amérique',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'las vegas',
        'flag' => 'images/flags/Drapeau Etats Unis.png',
        'continent' => 'amérique',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'qatar',
        'flag' => 'images/flags/Drapeau Qatar.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
    [
        'race_name' => 'abou dabi',
        'flag' => 'images/flags/Drapeau Emirats Arabes Unis.png',
        'continent' => 'asie',
        '2024' => true,
        '2025' => true,
        '2026' => null,
    ],
];

?>